config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get 'sign-in', to: 'session#sign_in', as: :sign_in
  post 'sign-in', to: 'session#login', as: :login
  get 'reset-password', to: 'session#reset_password', as: :reset_password
  get 'sign-up', to: 'session#sign_up', as: :sign_up
  get 'sign-out', to: 'session#sign_out', as: :sign_out
  get 'api/v1/session', to: 'session#get_session', as: :get_session

  namespace :admin do
    get 'master-data', to: 'admin#master_data'
    # period
    get 'period', to: 'period#index'
    get 'period/new', to: 'period#new'
    post 'period', to: 'period#create'
    put 'period/:id', to: 'period#update'
    get 'period/:id/edit', to: 'period#edit'
    get 'period/:id/delete', to: 'period#delete'
    # program-type
    get 'program-type', to: 'program_type#index'
    get 'program-type/new', to: 'program_type#new'
    post 'program-type', to: 'program_type#create'
    put 'program-type/:id', to: 'program_type#update'
    get 'program-type/:id/edit', to: 'program_type#edit'
    get 'program-type/:id/delete', to: 'program_type#delete'
    # industry
    get 'industry', to: 'industry#index'
    get 'industry/new', to: 'industry#new'
    post 'industry', to: 'industry#create'
    put 'industry/:id', to: 'industry#update'
    get 'industry/:id/edit', to: 'industry#edit'
    get 'industry/:id/delete', to: 'industry#delete'
    # specialism
    get 'specialism', to: 'specialism#index'
    get 'specialism/new', to: 'specialism#new'
    post 'specialism', to: 'specialism#create'
    put 'specialism/:id', to: 'specialism#update'
    get 'specialism/:id/edit', to: 'specialism#edit'
    get 'specialism/:id/delete', to: 'specialism#delete'
  end

  match '*unmatched', to: 'errors#not_found', via: :all
  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/session_controller.rb
# app/controllers/session_controller.rb
class SessionController < ApplicationController
  layout "blank"
  before_action :redirect_if_logged_in, only:[:sign_in]

  def sign_in
    
  end

  def login
    username = params[:username]
    password = params[:password]

    result = AuthService.login_by_username(username, password)


    if result[:success]
      user_data = result[:data]
      # Guardar en sesión
      #session[:user_token] = user_data['token'] || user_data[:token]
      #session[:user_id] = user_data['id'] || user_data[:id]
      session[:user] = user_data[:user]
      session[:tokens] = user_data[:tokens]
      session[:roles] = user_data[:roles]
      redirect_to root_path
    else
      flash[:alert] = result[:message]
      render :sign_in 
    end
  end

  def get_session
    if session.present? && session.to_hash.any?
      render json: {
        data: session.to_hash,
        message: 'datos del usuario logueado',
        error: nil,
        success: true
      }
    else
      render json: {
        data: nil,
        message: 'No hay sesión activa',
        error: 'Sesión no encontrada',
        success: false
      }, status: :not_found
    end
  end

  def sign_out
    reset_session
    flash[:notice] = "Sesión cerrada correctamente"
    redirect_to sign_in_path
  end
end

app/views/session/sign_in.html.erb
<%# app/views/sessions/sign_in.html.erb %>
<% content_for :title do %>Iniciar Sesión | TicketMaster<% end %>

<% content_for :extra_css do %>
  <style>
    .auth-wrapper {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #f8f9fa;
    }
    .auth-card {
      width: 100%;
      max-width: 400px;
    }

    .icon{
      margin-bottom: 30px;
    }
  </style>
<% end %>

<div class="auth-wrapper">
  <div class="auth-card card shadow-sm">
    <div class="card-body p-4">
      <div class="text-center mb-4">
        <img src="<%= assets_path %>img/logo-letters.png"  height="70" width="340" alt="" class="icon">
        <p class="text-muted">Ingresa tus credenciales para acceder al sistema</p>
      </div>
      <!-- Incluir partial de flash messages -->
      <%= render 'partials/flash_messages' %>

      <form method="post" action="<%= sign_in_path %>">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        
        <div class="mb-3">
          <label for="username" class="form-label">Usuario</label>
          <input type="text" name="username" id="username" 
                 class="form-control" required autofocus>
        </div>
        
        <div class="mb-3">
          <label for="password" class="form-label">Contraseña</label>
          <input type="password" name="password" id="password" 
                 class="form-control" required>
        </div>
        
        <div class="d-grid gap-2">
          <button type="submit" class="btn btn-primary">
            <i class="fa fa-sign-in me-1"></i> Ingresar
          </button>
          <button type="button" class="btn btn-success">
            <i class="fa fa-google me-1"></i> Ingresar con Google
          </button>
        </div>
      </form>

      <div class="text-center mt-3">
        <a href="<%= reset_password_path %>" class="text-decoration-none">
          ¿Olvidaste tu contraseña? 
        </a>
        <br>
        <a href="<%= sign_up_path %>" class="text-decoration-none">
          ¿Deseas crear una cuenta? 
        </a>
      </div>
    </div>
  </div>
</div>